// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Performance.Models
{
    [JsonObject(MemberSerialization.OptIn)]
    public class Singer
    {

        [JsonProperty("related_site_id")]
        public int RelatedSiteId { get; set; }

        [JsonProperty("is_site_artist")]
        public bool IsSiteArtist { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Song
    {

        [JsonProperty("albumtitle")]
        public string Albumtitle { get; set; }

        [JsonProperty("file_ext")]
        public string FileExt { get; set; }

        [JsonProperty("album")]
        public string Album { get; set; }

        [JsonProperty("ssid")]
        public string Ssid { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("sid")]
        public string Sid { get; set; }

        [JsonProperty("sha256")]
        public string Sha256 { get; set; }

        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("picture")]
        public string Picture { get; set; }

        [JsonProperty("alert_msg")]
        public string AlertMsg { get; set; }

        [JsonProperty("company")]
        public string Company { get; set; }

        [JsonProperty("rating_avg")]
        public double RatingAvg { get; set; }

        [JsonProperty("public_time")]
        public string PublicTime { get; set; }

        [JsonProperty("singers")]
        public IEnumerable<Singer> Singers { get; set; }

        [JsonProperty("like")]
        public string Like { get; set; }

        [JsonProperty("songlists_count")]
        public int SonglistsCount { get; set; }

        [JsonProperty("artist")]
        public string Artist { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("subtype")]
        public string Subtype { get; set; }

        [JsonProperty("length")]
        public int Length { get; set; }

        [JsonProperty("aid")]
        public string Aid { get; set; }

        [JsonProperty("kbps")]
        public string Kbps { get; set; }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class PlayList
    {

        [JsonProperty("r")]
        public int R { get; set; }

        [JsonProperty("is_show_quick_start")]
        public int IsShowQuickStart { get; set; }

        [JsonProperty("song")]
        public IEnumerable<Song> Song { get; set; }
    }

}
